num1 = int(input("Enter the First value :"))
num2 = int(input("Enter the Second value :"))
Operator = input("Enter a Operator :")

if Operator == "+":
    print(f"The addition of Two Values {num1 + num2}")
elif Operator == "-":
    print(f"The Subtraction of Two Values {num1 - num2}")
elif Operator == "*":
    print(f"The Subtraction of Two Values {num1 * num2}")
elif Operator == "/":
    print(f"The Subtraction of Two Values {num1 / num2}")
else:
    print("Enter valid Operator")


    